server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

user-service:
  url: ${USER_URL_PROD}

news-service:
  url: ${NEWS_URL_PROD}

spring:
  data:
    redis:
      host: 10.0.11.22
      port: 6379
